enabled: true

exclude:
  - ".github/workflows/**/*"

remote_files: []
auto: false
comments: false
statuses:
  differences: true     # Red when style differences are found
  no_differences: true  # Green when no differences are found
  error: true           # Red if we encounter errors restyling
request_review: none
labels: []
restylers_version: stable

restylers:
    - "*"
