name: Check
description: Formatter check

inputs:

  annotations:
    description: Should the script output annotations?
    default: true

runs:
  using: "composite"
  steps:
    - run: |
        cd ./hello/
        make
