name: comment-pr

on:
  workflow_run:
    workflows: ["pr-lint-verible"]
    types:
      - completed

jobs:
  Comment:
    name: Comment
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "linter-log"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/linter-log.zip', Buffer.from(download.data));
      - name: 'Unzip artifact'
        run: |
          unzip linter-log.zip
          cat ./verible-verilog-lint.log
          cat ./issue_num
      - id: get-comment-body
        run: |
          body=$(printf "\`\`\`" && cat ./verible-verilog-lint.log && printf "\`\`\`\n")
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::"$body"
      - id: get-pr-number
        run: |
          num=$(cat ./issue_num)
          echo ::set-output name=num::$num
      - run: |
          echo branch name: ${{ github.event.workflow_run.head_branch }}
      - name: Post comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          number: ${{ steps.get-pr-number.outputs.num }}
          check-only-first-line: "true"
          unique: "true"
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: ${{ steps.get-comment-body.outputs.body }}
