name: format-verible

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: antmicro/verible-actions@format
        with:
          paths: |
            ./rtl
