name: pr-format

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - run: |
          docker run --rm \
          --env "GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
          --volume /tmp:/tmp \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          restyled/restyler ${{ github.repository }}#${{ github.event.number}}
          
        shell: bash
