name: test annotations action

on:
  push:
  pull_request:

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Getting code
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1

    - name: Install dependencies
      run: npm install -g make git clang-format

    - name: Run formatter
      run: |
        chmod +x ./run-formatter.sh
        /usr/bin/bash ./run-formatter.sh
        DIFF_LOG=`/usr/bin/bash ./run-formatter.sh`

    - name: Generate annotations
      run: |
        DIFF_TEXT=`cat $DIFF_LOG`
        LINE=`cut -sd "@" -f3 $DIFF_LOG | cut -d "," -f2 | cut -f1 -d " "`
        echo "::error file=./hello/hello.c,line=$LINE,col=1::$DIFF_TEXT"
