name: test annotations action

on:
  push:
  pull_request:

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Getting code
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1

    - name: Install dependencies
      run: npm install -g make git

    - name: Run formatter
      run: echo "here foramtter will be called"

    - name: Generate annotations
      run: |
        text="test annotation"
        echo "::error file=./hello/hello.c,line=1,col=1::$text"
