name: test annotations action

on:
  push:
  pull_request:

inputs:

  annotations:
    description: Should the script output annotations?
    default: true

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Getting code
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1

    - name: Install dependencies
      run: npm install -g make

    - name: Run sample app
      run: |
        cd ./hello/
        make
