name: test annotations action

on:
  push:
  pull_request:

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Getting code
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1

    - name: Install dependencies
      run: npm install -g make git clang-format

    - name: Run formatter and generate annotations
      run: |
        chmod +x ./run-formatter.sh
        ./run-formatter.sh
        DIFF_LOG=`/usr/bin/bash ./run-formatter.sh`
        DIFF_TEXT=`cat $DIFF_LOG`
        DIFF_TEXT="${DIFF_TEXT//'%'/'%25'}"
        DIFF_TEXT="${DIFF_TEXT//$'\n'/'%0A'}"
        DIFF_TEXT="${DIFF_TEXT//$'\r'/'%0D'}"
        echo $DIFF_TEXT
        LINE=`cut -sd "@" -f3 $DIFF_LOG | cut -d "," -f2 | cut -f1 -d " "`
        echo $LINE
        echo "::error file=./hello/hello.c,line=$LINE,col=1::$DIFF_TEXT"
