name: upload-event-file

on:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_EVENT_PATH"
          cat "$GITHUB_EVENT_PATH"
      - name: Copy event file
        run: cp "$GITHUB_EVENT_PATH" ./event.json

      - name: Upload event file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: event.json
          path: event.json
