name: verible-trigger-receive
on:
  workflow_run:
    workflows: verible-trigger-send
    types:
      - completed

jobs:
  verible-review:
    runs-on: ubuntu-latest
    steps:
      - uses: chipsalliance/verible-formatter-action/trigger-receive@main
      - name: Run Verible action
        uses: chipsalliance/verible-formatter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
