name: verible-trigger-receive
on:
  workflow_run:
    workflows: verible-trigger-send
    types:
      - completed

jobs:
  verible-review:
    runs-on: ubuntu-latest
    steps:
      - uses: antmicro/verible-linter-action/trigger-receive@triggers
      - name: Run Verible action
        uses: chipsalliance/verible-linter-action@triggers
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
